# Generated by Django 4.0 on 2021-12-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('booktitle', models.CharField(max_length=50)),
                ('bookauthor', models.CharField(max_length=50)),
            ],
        ),
    ]
