# Generated by Django 4.0 on 2021-12-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('booktitle', models.CharField(max_length=50)),
            ],
        ),
    ]
