# Generated by Django 4.0 on 2022-01-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7_1', '0002_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name', 'booktitle')},
        ),
    ]
